services:
  - type: web
    name: calm-nest
    env: node
    buildCommand: |
      npm install --prefix backend
      pip install -r requirements.txt
    startCommand: node backend/app.js
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    autoDeploy: true
